### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yxdxx** [liranringel/structure#4]
I was writing a program  send telegram with TCPSTREAM . send an XML file with an head of the length of the XML characters.  
let s = structure!(">4S716s");
            let buffsend:Vec<u8> =s.pack(lengthstring.as_bytes(),contentbuff).unwrap();
turns out an error:
buffer size in format: 3, actual size: 4", I wanna to padding the left with 0000, how can I do with it .seems > does't work .  if I use s, no error ,but the telegram seems still not correct in the head.
also how can I replace with 716. the length of the XML . everytime  the length will change.

**Comment by liranringel** [comment]
Hey!
I glad to see that people use this crate, though I doubt it's the right solution for sending xml.
`structure` is really good for writing fixed-size buffers, but you want a variable size buffer.

If you still think it could work for you, it could be useful if you upload your hole program or describe better what's the desired output.

Using 's' is the right thing to do if you want to pad your buffer with zeros, but it obviously won't play well with xml, which is a text format.

**Comment by yxdxx** [comment]
thank you for your reply...
I have write a python code with module struct . it works. 
if possible, you can give a version of rust code. that will be nice of you..
the xml1 does't seem to display.. I put the attachment as xml content.
[CreateVMDT_066_01.txt](https://github.com/liranringel/structure/files/1323523/CreateVMDT_066_01.txt)



xml1 = """<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<root>
  <header eventId="0" eventName="partProcessed" version="1.0" eventSwitch="1" contentType="3" timeStamp="2016-10-17T08:14:30.2623395+08:00">
    <location lineNo="5" statNo="1000" statIdx="1" fuNo="1" workPos="1" toolPos="1" application="PLC" processName="" processNo="10401" />
  </header>
  <event>
    <partProcessed identifier="test123" />
  </event>
  <body>
    <structs>
      <resHead nioBits="0" result="1" typeNo="0261520176" typeVar="99" workingCode="0" />
    </structs>
    <items>
      <item name="RouteList" value="L5_with_lid_fitting" dataType="8" />
      <item name="nextProcessNo" value="9033" dataType="3" />
    </items>
  </body>
</root>"""

import struct
import socket


buffer = struct.pack('!i' + str(len(xml1)) + 's', len(xml1) + 4,
                     xml1.encode("utf8"))
Host = "10.174.xxx.xxx"
Port = 55065
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((Host, Port))
s.sendall(buffer)
buf = s.recv(1024)
s.close()
result = buf[4:].decode("utf8")
#print(result)
if 'returnCode="0"' in result:
    print("modified success")
else:
    print("check your telegram")

**Comment by liranringel** [comment]
You create a format string at runtime, but it's not supported by this crate (and probably will never be).
Rust is a static typed language. Therefore it's not possible to process the format string at runtime without sacrifying the type safety you get (pack gets the right types as parameters, and unpack returns the right types).
Processing the format string at runtime is a feature that should be considered, but I've yet to think of a good way to do it. If the interface won't be easy, it will miss the purpose of this crate.

Since you're trying to parse xml, I'd really want you to try serde: https://github.com/RReverser/serde-xml-rs

**Comment by yxdxx** [comment]
thank you very much. you are really nice person.  I will try to understand the language more deep..^_^,also try to use serde.

**Comment by liranringel** [comment]
Good luck :)
