### ISSUE TITLE
Using structure!(variable)

### ISSUE THREAD

**Issue by dpineiden** [liranringel/structure#9]
Hi, instead of usinge a harcoded string (that works fine) I need to use a variable to generate the struct.
I've tried different ways 
from a Vec<String>
take the conv:
let conv = vector[0].as_str();
then
structure!(&conv)
and yet shows 

   = help: message: structure!() macro takes a literal string as an argument
   = note: this error originates in the macro `structure` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by liranringel** [comment]
I'm sorry, but that's a limitation the library currently has.
That's because it creates code on compile-time that knows how to parse the struct.
This is because I wanted `pack` and `unpack` methods to be aware of the types it gets/returns on compile time.

**Comment by dpineiden** [comment]
Thanks, has sense.
By the way i build this https://gitlab.com/pineiden/gsof-trimble-rust
with your crate, very useful ;)

**Comment by liranringel** [comment]
> Thanks, has sense. By the way i build this https://gitlab.com/pineiden/gsof-trimble-rust with your crate, very useful ;)

Glad to hear :)
